# Generated by Django 4.2.2 on 2023-09-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member", old_name="Email", new_name="firstname",
        ),
        migrations.RenameField(
            model_name="member", old_name="Name", new_name="lastname",
        ),
    ]
